# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm audit fix
          npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: themeartifact
          retention-days: 3
          path: |
            build
            !build/**/*.md
      # Take data from a previous step/job
      - name: Download theme data
        uses: actions/download-artifact@v3
        with:
          name: themeartifact
          path: theme
      # Deploy
      - name: Deploy to the test subreddit
        uses: redditnfl/publish-reddit-stylesheet-action@v1.0.0
        with:
          subreddit: ThisWoomyIsSalty
          path: theme
          skip images: true
        env:
          praw_client_id: ${{ secrets.style_publisher_praw_client_id }}
          praw_client_secret: ${{ secrets.style_publisher_praw_client_secret }}
          praw_refresh_token: ${{ secrets.style_publisher_praw_refresh_token }}
